export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTRATION_BEGIN = "REGISTRATION_BEGIN";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const AUTHORIZE_USER = "AUTHORIZE_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const UI_LOGIN_FORM_CHANGE = "UI_LOGIN_FORM_CHANGE";
export const UI_REGISTER_FORM_CHANGE = "UI_REGISTER_FORM_CHANGE";
