export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_UNDEFINED = "LOGIN_UNDEFINED";

export const REGISTRATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_UNDEFINED = "REGISTRATION_UNDEFINED";
